export { H1 } from "./h1"
export { H2 } from "./h2"
export { H3 } from "./h3"
export { H4 } from "./h4"
// export { P } from "./p"
// export { Blockquote } from "./blockquote"
// export { Code } from "./code"
// export { TextHr } from "./text-hr"
// export { InlineCode } from "./inline-code"
// export { MyLink } from "./my-link"
// export { List } from "./list"
// export { Hr } from "./hr"
